Repository Pooptube/Pooptube, pull requests merged in 2023-09, with the labels that each got.

#1 뷰페이저, 탭레이아웃 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/pooptube/MainActivity.kt
  app/src/main/java/com/example/pooptube/home/HomeFragment.kt
  app/src/main/java/com/example/pooptube/main/MainActivity.kt
  app/src/main/java/com/example/pooptube/main/MainPagerAdapter.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosFragment.kt
  app/src/main/java/com/example/pooptube/search/SearchFragment.kt
  app/src/main/res/drawable/ic_dashboard.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_videos.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/themes.xml
Labels: feat

#2 API Key, URL을 설정
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: feat

#5 [design] : UI 레이아웃 디자인
  app/src/main/res/layout/fragment_my_videos.xml
Labels: design

#7 [DESIGN] 홈에 관련된 UI작업
  app/src/main/java/com/example/pooptube/home/HomeFilterModel.kt
  app/src/main/java/com/example/pooptube/home/HomeVideoModel.kt
  app/src/main/java/com/example/pooptube/home/HomeViewModel.kt
  app/src/main/res/layout/filter_chip.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_item_video.xml
  app/src/main/res/values/style.xml
Labels: design

#9 [FEAT]:Home Adapter 연결
  app/build.gradle
  app/src/main/java/com/example/pooptube/home/HomeChipAdapter.kt
  app/src/main/java/com/example/pooptube/home/HomeFragment.kt
  app/src/main/java/com/example/pooptube/home/HomeVideoAdapter.kt
  app/src/main/res/layout/fragment_search.xml
Labels: feat

#10 [FEAT] : retrofit 셋팅
  app/build.gradle
  app/src/main/java/com/example/pooptube/main/CategoryChannelsService.kt
  app/src/main/java/com/example/pooptube/main/CategoryVideosService.kt
  app/src/main/java/com/example/pooptube/main/MainActivity.kt
  app/src/main/java/com/example/pooptube/main/MostPopularVideosService.kt
  app/src/main/java/com/example/pooptube/main/VideosModel.kt
  app/src/main/java/com/example/pooptube/main/VideosModelList.kt
Labels: feat

#12 TabIndicator 숨기기, VideoDetail 레이아웃
  app/build.gradle
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailFragment.kt
  app/src/main/res/drawable/ic_like_empty.xml
  app/src/main/res/drawable/ic_like_filled.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/videodetail_button_bg.xml
  app/src/main/res/drawable/videodetail_sample.jpg
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_video_detail.xml
Labels: design

#13 [FEAT] fragment_search 레이아웃 기본 작업
  app/src/main/res/layout/fragment_search.xml
Labels: design

#15 Feat/rvitem
  app/build.gradle
  app/src/main/java/com/example/pooptube/main/VideosModel.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosAdapter.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosFragment.kt
  app/src/main/res/layout/fragment_my_videos.xml
  app/src/main/res/layout/my_videos_item.xml
Labels: design, feat

#16 Feat/retrofit2 : 레트로핏 구현
  app/build.gradle
  app/src/main/java/com/example/pooptube/main/ApiConfig.kt
  app/src/main/java/com/example/pooptube/main/CategoryChannelsService.kt
  app/src/main/java/com/example/pooptube/main/CategoryVideosService.kt
  app/src/main/java/com/example/pooptube/main/MainActivity.kt
  app/src/main/java/com/example/pooptube/main/MostPopularVideosService.kt
  app/src/main/java/com/example/pooptube/main/VideosApiService.kt
  app/src/main/java/com/example/pooptube/main/VideosModel.kt
  app/src/main/java/com/example/pooptube/main/VideosModelList.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosAdapter.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosDiffUtil.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosFragment.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosModel.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosViewModel.kt
  app/src/main/java/com/example/pooptube/myvideos/SnippetYt.kt
  app/src/main/java/com/example/pooptube/myvideos/ThumbnailsYt.kt
  app/src/main/res/layout/my_videos_item.xml
Labels: fix, design, feat

#18 [FEAT]: 레트로핏 적용
  app/build.gradle
  app/src/main/java/com/example/pooptube/home/HomeFragment.kt
  app/src/main/java/com/example/pooptube/home/HomeVideoAdapter.kt
  app/src/main/java/com/example/pooptube/home/HomeVideoModel.kt
  app/src/main/java/com/example/pooptube/main/ApiConfig.kt
  app/src/main/java/com/example/pooptube/main/VideosApiService.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosAdapter.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosDiffUtil.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosModel.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosViewModel.kt
  app/src/main/res/layout/fragment_search.xml
Labels: feat

#21 VideoDetail 연결, 레이아웃 수정
  app/build.gradle
  app/src/main/java/com/example/pooptube/home/HomeFragment.kt
  app/src/main/java/com/example/pooptube/home/HomeVideoAdapter.kt
  app/src/main/java/com/example/pooptube/main/MainActivity.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosAdapter.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosFragment.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailFragment.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailModel.kt
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/videodetail_btn_bg.xml
  app/src/main/res/drawable/videodetail_btn_down_bg.xml
  app/src/main/res/drawable/videodetail_button_bg.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_video_detail.xml
Labels: design, feat

#26 [DESIGN] Chip UI 작업
  app/src/main/java/com/example/pooptube/home/HomeFragment.kt
  app/src/main/java/com/example/pooptube/home/HomeVideoModel.kt
  app/src/main/res/color/chip_background_selector.xml
  app/src/main/res/layout/filter_chip.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/style.xml
Labels: design

#28 [FEAT]: Chip 기능 구현
  app/src/main/java/com/example/pooptube/home/HomeChipAdapter.kt
  app/src/main/java/com/example/pooptube/home/HomeFilterModel.kt
  app/src/main/java/com/example/pooptube/home/HomeFragment.kt
  app/src/main/java/com/example/pooptube/home/HomeVideoAdapter.kt
  app/src/main/java/com/example/pooptube/home/HomeVideoModel.kt
  app/src/main/java/com/example/pooptube/main/VideosApiService.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosModel.kt
  app/src/main/res/layout/filter_chip.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_item_video.xml
Labels: feat

#29 btnLike 기능 추가 (+ btnDown 버그 수정)
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailFragment.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailModel.kt
Labels: fix, feat

#34 [FEAT] : search 패딩값 세부 조절
  app/src/main/java/com/example/pooptube/myvideos/MyVideosAdapter.kt
  app/src/main/java/com/example/pooptube/search/SearchFragment.kt
Labels: feat

#35 [FEAT] : search 패딩값 세부 조절 part2
  app/src/main/java/com/example/pooptube/myvideos/MyVideosAdapter.kt
  app/src/main/java/com/example/pooptube/search/SearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/my_videos_item.xml
Labels: feat

#36 VideoDetail에 데이터 전달 및 표시
  app/build.gradle
  app/src/main/java/com/example/pooptube/home/HomeFragment.kt
  app/src/main/java/com/example/pooptube/main/MainActivity.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosFragment.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosModel.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailFragment.kt
  app/src/main/res/layout/fragment_video_detail.xml
Labels: fix, feat

#39 Feature/searchchip : 레이아웃 수정 및 recyclerview 적용
  app/src/main/java/com/example/pooptube/search/SearchFragment.kt
  app/src/main/res/layout/fragment_my_videos.xml
  app/src/main/res/layout/fragment_search.xml
Labels: design, feat

#40 [FEAT]: HomeViewModel
  app/src/main/java/com/example/pooptube/home/HomeFragment.kt
  app/src/main/java/com/example/pooptube/home/HomeViewModel.kt
Labels: feat

#43 Search 페이지와 VideoDetail 연결
  app/src/main/java/com/example/pooptube/main/MainActivity.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosModel.kt
  app/src/main/java/com/example/pooptube/search/SearchFragment.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailFragment.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailModel.kt
  app/src/main/res/drawable/ic_like_empty.xml
  app/src/main/res/drawable/ic_like_filled.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/layout/fragment_video_detail.xml
Labels: fix, feat

#45 SearchFragment에서의 adapter 문제 해결
  app/src/main/java/com/example/pooptube/search/SearchFragment.kt
Labels: fix, conflict
