Repository Pooptube/Pooptube, pull requests merged in 2023-10, with the labels that each got.

#47 Home과 VideoDetail 연결
  app/src/main/java/com/example/pooptube/home/HomeFragment.kt
  app/src/main/java/com/example/pooptube/home/HomeVideoAdapter.kt
  app/src/main/java/com/example/pooptube/home/HomeVideoModel.kt
  app/src/main/java/com/example/pooptube/main/MainActivity.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosFragment.kt
  app/src/main/java/com/example/pooptube/search/SearchFragment.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailFragment.kt
Labels: fix, feat

#49 [FEAT]: DetailPage에 넘겨줄 description Home에 추가
  app/src/main/java/com/example/pooptube/home/HomeVideoModel.kt
  app/src/main/java/com/example/pooptube/home/HomeViewModel.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailFragment.kt
Labels: feat

#50 chip리싸이클러뷰 커스텀리싸이클러로 변경후, chip 부분 viewpager2 동작 x
  app/src/main/java/com/example/pooptube/home/ChipCustomRecyclerView.kt
  app/src/main/java/com/example/pooptube/home/HomeFragment.kt
  app/src/main/java/com/example/pooptube/main/MainActivity.kt
  app/src/main/res/layout/fragment_home.xml
Labels: feat

#51 Toolbar 및 TabLayout 제어, 조회수 및 업로드날짜 format
  app/src/main/java/com/example/pooptube/main/MainActivity.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailFragment.kt
  app/src/main/res/drawable/ic_poop.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/custom_toolbar.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/layout/home_item_video.xml
  app/src/main/res/values/themes.xml
Labels: design, feat

#53 [DESIGN]: TabLayout, ToolBar 수정
  app/src/main/java/com/example/pooptube/main/MainActivity.kt
  app/src/main/res/color/main_tab_text_color_selector.xml
  app/src/main/res/layout/custom_toolbar.xml
  app/src/main/res/values/themes.xml
Labels: design

#54 좋아요 SharedPreferences
  app/src/main/java/com/example/pooptube/main/Constants.kt
  app/src/main/java/com/example/pooptube/main/MainActivity.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosFragment.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailFragment.kt
  app/src/main/res/layout/fragment_video_detail.xml
Labels: fix, feat

#55 [REFACTOR]: Utils에 조회수와, 날짜를 담아놈
  app/src/main/java/com/example/pooptube/home/HomeVideoAdapter.kt
  app/src/main/java/com/example/pooptube/main/Utils.kt
Labels: refactor

#57 ApiConfig interceptor 추가
  app/build.gradle
  app/src/main/java/com/example/pooptube/main/ApiConfig.kt
  app/src/main/java/com/example/pooptube/search/SearchViewModel.kt
Labels: feat

#59 Utils 적용 및 수정
  app/src/main/java/com/example/pooptube/home/HomeVideoAdapter.kt
  app/src/main/java/com/example/pooptube/main/Utils.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailFragment.kt
Labels: fix, refactor

#60 Feature/searchchip
  app/src/main/java/com/example/pooptube/main/VideosApiService.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosFragment.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosModel.kt
  app/src/main/java/com/example/pooptube/search/SearchFragment.kt
  app/src/main/java/com/example/pooptube/search/SearchViewModel.kt
Labels: conflict, feat

#64 README
  README.md
Labels: docs

#65 [HELP] : 우리팀 화이팅
  app/src/main/java/com/example/pooptube/myvideos/MyVideosAdapter.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosFragment.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosViewModel.kt
  app/src/main/java/com/example/pooptube/search/SearchFragment.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailFragment.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailModel.kt
Labels: feat

#67 [Fix] Detail Page 오류 수정, MyVideo UI 수정
  app/src/main/java/com/example/pooptube/main/MainActivity.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosFragment.kt
  app/src/main/java/com/example/pooptube/myvideos/MyVideosViewModel.kt
  app/src/main/java/com/example/pooptube/myvideos/SnippetYt.kt
  app/src/main/java/com/example/pooptube/myvideos/ThumbnailsYt.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailFragment.kt
  app/src/main/java/com/example/pooptube/videodetail/VideoDetailModel.kt
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/layout/my_videos_item.xml
Labels: fix

#68 Feature/detail sp
  app/src/main/java/com/example/pooptube/search/SearchFragment.kt
  app/src/main/res/drawable/videodetail_bg.jpg
  app/src/main/res/drawable/videodetail_profile.jpg
  app/src/main/res/layout/fragment_my_videos.xml
  app/src/main/res/layout/fragment_search.xml
Labels: design, feat

#70 앱 아이콘 설정 💩
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: design

#71 Feature/detail sp
  README.md
  app/src/main/java/com/example/pooptube/myvideos/SnippetYt.kt
  app/src/main/java/com/example/pooptube/myvideos/ThumbnailsYt.kt
Labels: docs
